spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tour?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Logging Configuration
logging.level.root=INFO
logging.level.com.tours=DEBUG

# Log file location
logging.file.name=logs/app.log

# Log rotation
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.total-size-cap=1GB
logging.logback.rollingpolicy.max-history=30


# Session Configuration
server.servlet.session.timeout=30m
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true


# Server Configuration
server.tomcat.connection-timeout=20000
server.tomcat.max-connections=200
server.tomcat.threads.max=200


# Default Admin Configuration
app.admin.name=Admin
app.admin.email=admin@tours.com
app.admin.password=Rakesh@123
app.admin.contact=9999999999




# Multipart File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB


# OAuth2 Configuration
# Google Configuration
spring.security.oauth2.client.registration.google.client-name=google
spring.security.oauth2.client.registration.google.client-id=<google-client-id>
spring.security.oauth2.client.registration.google.client-secret=<google-secret-id>
spring.security.oauth2.client.registration.google.scope=openid,email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google


spring.main.allow-circular-references=true


# Cloudinary Configuration
cloudinary.cloud-name=<cloud-name>
cloudinary.api-key=<api-key>
cloudinary.api-secret=<secret-id>


# Stripe Configuration
stripe.secret.key=<secret-key>
stripe.publishable.key= <publishable-key>